MyDemo:Mouse.h Mouse.cpp TemplateMatch.h TemplateMatch.cpp TestTmpl.cpp
	g++ -g Mouse.h Mouse.cpp TemplateMatch.h TemplateMatch.cpp TestTmpl.cpp -lgdi32 `pkg-config --cflags --libs opencv` -std=c++11 -o MyDemo
clean:
	rm -rf TestTmpl
